# Dataset
dataset: &dataset !DIV2KDataloader
  batch_size: 32
  patch_size: 128
  scale: &scale 4

# Optimizers
optimizers: &optimizers
  weight_optimizer: 
    name: Adam
    params:
      lr: 0.001
    scheduler:
      name: CosineAnnealingLR
      params:
        T_max: 180000

training_loop: &training_loop !TrainingLoop
  dataset: *dataset
  model: !BinaryScalex4BaselineV0
  loss: !L1Loss
  train_metrics:
    PSNR: !PSNR
      min_val: 0
      max_val: 255
      boundary_size: *scale
  val_metrics:
    PSNR: !PSNR
      min_val: 0
      max_val: 255
      boundary_size: *scale

task: !Task
  training_loop: *training_loop
  epochs: 7200 # 180000 iterations
  optimizers: *optimizers
  model_saver:
    monitor: "val_PSNR"
    mode: max
  check_val_every_n_epochs: 50
