# Dataset
dataset: &dataset !DIV2KDataloader
  batch_size: 32
  patch_size: 96
  scale: &scale 2

# Optimizers
optimizers: &optimizers
  weight_optimizer: 
    name: Adam
    params:
      lr: 0.0002
    scheduler:
      name: MultiStepLR
      params:
        milestones: [100000] # 2/3 of total iterations
        gamma: 0.5

training_loop: &training_loop !TrainingLoop
  dataset: *dataset
  model: !BinaryScalex2BaselineV0
  loss: !L1Loss
  train_metrics:
    PSNR: !PSNR
      min_val: 0
      max_val: 255
      boundary_size: *scale
  val_metrics:
    PSNR: !PSNR
      min_val: 0
      max_val: 255
      boundary_size: *scale

task: !Task
  training_loop: *training_loop
  epochs: 6000 # 150000 iterations
  optimizers: *optimizers
  model_saver:
    monitor: "val_PSNR"
    mode: max
  check_val_every_n_epochs: 50
